# Generated by Django 5.0 on 2024-01-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_images_book_image'),
        ('transaction', '0002_rename_account_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.book', null=True),
        ),
    ]
