# Generated by Django 5.0 on 2024-01-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='book',
        ),
    ]
